In [5]:
from tabulate import tabulate
# Fungsi untuk melakukan seleksi berdasarkan IPK tertinggi
def seleksi_berdasarkan_ipk_tertinggi(data_mahasiswa, kriteria):
    sorted_mahasiswa = sorted(data_mahasiswa, key=lambda x: x['IPK'], reverse=True)
    return sorted_mahasiswa[kriteria[0]-1:kriteria[1]]

# Fungsi untuk menampilkan hasil seleksi dalam tabel
def tampilkan_hasil_seleksi_table(fakultas, mahasiswa_diterima):
    headers = ["Nama", "IPK"]
    table = [[mhs['nama'], mhs['IPK']] for mhs in mahasiswa_diterima]
    print(f"Mahasiswa diterima di {fakultas}:")
    print(tabulate(table, headers=headers, tablefmt="grid"))

# Data mahasiswa Fakultas Teknologi Informasi
mahasiswa_ti = [
    {'nama': 'Mahasiswa1', 'IPK': 3.8},
    {'nama': 'Mahasiswa2', 'IPK': 3.5},
    {'nama': 'Mahasiswa3', 'IPK': 3.9},
    {'nama': 'Mahasiswa4', 'IPK': 3.7},
    {'nama': 'Mahasiswa5', 'IPK': 3.6},
    {'nama': 'Mahasiswa6', 'IPK': 3.2},
    {'nama': 'Mahasiswa7', 'IPK': 3.4},
    {'nama': 'Mahasiswa8', 'IPK': 3.9},
    {'nama': 'Mahasiswa9', 'IPK': 3.3},
    {'nama': 'Mahasiswa10', 'IPK': 3.8},
    {'nama': 'Mahasiswa11', 'IPK': 3.6},
    {'nama': 'Mahasiswa12', 'IPK': 3.5},
    {'nama': 'Mahasiswa13', 'IPK': 3.7},
    {'nama': 'Mahasiswa14', 'IPK': 3.9},
    {'nama': 'Mahasiswa15', 'IPK': 3.2},
    {'nama': 'Mahasiswa16', 'IPK': 3.8},
    {'nama': 'Mahasiswa17', 'IPK': 3.7},
    {'nama': 'Mahasiswa18', 'IPK': 3.6},
    {'nama': 'Mahasiswa19', 'IPK': 3.5},
    {'nama': 'Mahasiswa20', 'IPK': 3.4},
    {'nama': 'Mahasiswa21', 'IPK': 3.3},
    {'nama': 'Mahasiswa22', 'IPK': 3.9},
    {'nama': 'Mahasiswa23', 'IPK': 3.8},
    {'nama': 'Mahasiswa24', 'IPK': 3.7},
    {'nama': 'Mahasiswa25', 'IPK': 3.6},
    {'nama': 'Mahasiswa26', 'IPK': 3.5},
    {'nama': 'Mahasiswa27', 'IPK': 3.4},
    {'nama': 'Mahasiswa28', 'IPK': 3.3},
    {'nama': 'Mahasiswa29', 'IPK': 3.9},
    {'nama': 'Mahasiswa30', 'IPK': 3.8},
    {'nama': 'Mahasiswa31', 'IPK': 3.7},
    {'nama': 'Mahasiswa32', 'IPK': 3.6},
    {'nama': 'Mahasiswa33', 'IPK': 3.5},
    {'nama': 'Mahasiswa34', 'IPK': 3.4},
    {'nama': 'Mahasiswa35', 'IPK': 3.3},
    {'nama': 'Mahasiswa36', 'IPK': 3.9},
    {'nama': 'Mahasiswa37', 'IPK': 3.8},
    {'nama': 'Mahasiswa38', 'IPK': 3.7},
    {'nama': 'Mahasiswa39', 'IPK': 3.6},
    {'nama': 'Mahasiswa40', 'IPK': 3.5},
    {'nama': 'Mahasiswa41', 'IPK': 3.4},
    {'nama': 'Mahasiswa42', 'IPK': 3.3},
    {'nama': 'Mahasiswa43', 'IPK': 3.9},
    {'nama': 'Mahasiswa44', 'IPK': 3.8},
    {'nama': 'Mahasiswa45', 'IPK': 3.7},
]


# Seleksi berdasarkan kriteria IPK tertinggi
kriteria_sains_data = (1, 15)
kriteria_teknik_informatika = (16, 30)
kriteria_sistem_informasi = (31, 45)

mahasiswa_sains_data = seleksi_berdasarkan_ipk_tertinggi(mahasiswa_ti, kriteria_sains_data)
mahasiswa_teknik_informatika = seleksi_berdasarkan_ipk_tertinggi(mahasiswa_ti, kriteria_teknik_informatika)
mahasiswa_sistem_informasi = seleksi_berdasarkan_ipk_tertinggi(mahasiswa_ti, kriteria_sistem_informasi)

# Menampilkan hasil seleksi dalam tabel
tampilkan_hasil_seleksi_table("Sains Data", mahasiswa_sains_data)
tampilkan_hasil_seleksi_table("Teknik Informatika", mahasiswa_teknik_informatika)
tampilkan_hasil_seleksi_table("Sistem Informasi", mahasiswa_sistem_informasi)

Mahasiswa diterima di Sains Data:
+-------------+-------+
| Nama        |   IPK |
+=============+=======+
| Mahasiswa3  |   3.9 |
+-------------+-------+
| Mahasiswa8  |   3.9 |
+-------------+-------+
| Mahasiswa14 |   3.9 |
+-------------+-------+
| Mahasiswa22 |   3.9 |
+-------------+-------+
| Mahasiswa29 |   3.9 |
+-------------+-------+
| Mahasiswa36 |   3.9 |
+-------------+-------+
| Mahasiswa43 |   3.9 |
+-------------+-------+
| Mahasiswa1  |   3.8 |
+-------------+-------+
| Mahasiswa10 |   3.8 |
+-------------+-------+
| Mahasiswa16 |   3.8 |
+-------------+-------+
| Mahasiswa23 |   3.8 |
+-------------+-------+
| Mahasiswa30 |   3.8 |
+-------------+-------+
| Mahasiswa37 |   3.8 |
+-------------+-------+
| Mahasiswa44 |   3.8 |
+-------------+-------+
| Mahasiswa4  |   3.7 |
+-------------+-------+
Mahasiswa diterima di Teknik Informatika:
+-------------+-------+
| Nama        |   IPK |
+=============+=======+
| Mahasiswa13 |   3.7 |
+-------------+-------+
| Mahasiswa17 |   3.7 |
+-------------+-------+
| Mahasiswa24 |   3.7 |
+-------------+-------+
| Mahasiswa31 |   3.7 |
+-------------+-------+
| Mahasiswa38 |   3.7 |
+-------------+-------+
| Mahasiswa45 |   3.7 |
+-------------+-------+
| Mahasiswa5  |   3.6 |
+-------------+-------+
| Mahasiswa11 |   3.6 |
+-------------+-------+
| Mahasiswa18 |   3.6 |
+-------------+-------+
| Mahasiswa25 |   3.6 |
+-------------+-------+
| Mahasiswa32 |   3.6 |
+-------------+-------+
| Mahasiswa39 |   3.6 |
+-------------+-------+
| Mahasiswa2  |   3.5 |
+-------------+-------+
| Mahasiswa12 |   3.5 |
+-------------+-------+
| Mahasiswa19 |   3.5 |
+-------------+-------+
Mahasiswa diterima di Sistem Informasi:
+-------------+-------+
| Nama        |   IPK |
+=============+=======+
| Mahasiswa26 |   3.5 |
+-------------+-------+
| Mahasiswa33 |   3.5 |
+-------------+-------+
| Mahasiswa40 |   3.5 |
+-------------+-------+
| Mahasiswa7  |   3.4 |
+-------------+-------+
| Mahasiswa20 |   3.4 |
+-------------+-------+
| Mahasiswa27 |   3.4 |
+-------------+-------+
| Mahasiswa34 |   3.4 |
+-------------+-------+
| Mahasiswa41 |   3.4 |
+-------------+-------+
| Mahasiswa9  |   3.3 |
+-------------+-------+
| Mahasiswa21 |   3.3 |
+-------------+-------+
| Mahasiswa28 |   3.3 |
+-------------+-------+
| Mahasiswa35 |   3.3 |
+-------------+-------+
| Mahasiswa42 |   3.3 |
+-------------+-------+
| Mahasiswa6  |   3.2 |
+-------------+-------+
| Mahasiswa15 |   3.2 |
+-------------+-------+